import {readFile, writeFile, mkdir} from 'node:fs/promises';
import path from 'node:path';
import {readDocuments, markdownBody, documentDigest} from '../text-docs/index.mjs';
import {classify} from './model.mjs';
export {classify} from './model.mjs';

export function documentRoute(name, source) {
  const slug = source.match(/^slug:\s*(\S+)/m)?.[1];
  if (slug) {
    if (!slug.startsWith('/') || slug.includes('..')) throw new Error('Unsupported document slug: ' + name);
    return slug;
  }
  return '/' + name.replace(/\.md$/, '').replace(/(^|\/)index$/, '$1');
}
export function plainText(source) {
  return markdownBody(source)
    .replace(/<details>\s*<summary>(?:Maintainer sources|For Pactrun maintainers) \(optional\)<\/summary>[\s\S]*?<\/details>/g, '')
    .replace(/^(#{1,6}[ \t]+[^\n]+?)[ \t]+\{#[^\n}]+\}[ \t]*$/gm, (_, heading) => heading)
    .replace(/<!--[\s\S]*?-->/g, '').replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/<[^>\n]+>/g, ' ').replace(/[#*\x60|]/g, ' ').replace(/\s+/g, ' ').trim();
}
export function requirementAnchors(source) {
  const anchors = {};
  for (const match of source.matchAll(/^#{1,6} (PR-REQ-\d+)\b([^\n]*)/gm)) {
    const heading = match[1] + match[2];
    const explicit = heading.match(/\s+\{#([^}]+)\}\s*$/)?.[1];
    // The bounded requirement-heading grammar is checked against rendered HTML at build.
    anchors[match[1]] = explicit ?? heading.toLowerCase()
      .replace(/[^\p{L}\p{N}_\-\s]/gu, '').replace(/\s/g, '-');
  }
  return anchors;
}

export async function validateRequirementAnchors(outDir, pages) {
  for (const page of pages.filter(page => Object.keys(page.requirementAnchors).length)) {
    const relative = page.url.slice(1).replace(/\/$/, '');
    let html;
    for (const file of [path.join(outDir, relative + '.html'), path.join(outDir, relative, 'index.html')]) {
      try { html = await readFile(file, 'utf8'); break; }
      catch (error) { if (error.code !== 'ENOENT') throw error; }
    }
    if (html === undefined) throw new Error('Missing rendered contract: ' + page.source);
    for (const [id, anchor] of Object.entries(page.requirementAnchors)) {
      if (!html.includes('id="' + anchor + '"')) throw new Error('Unverified requirement anchor: ' + id + ' in ' + page.source);
    }
  }
}

export function makeCatalog(documents) {
  const pages = documents.filter(([name]) => name.endsWith('.md') && !name.startsWith('agents/')).map(([name, source]) => ({
    source: name,
    title: source.match(/^title:\s*(.+)$/m)?.[1]?.replace(/^['"]|['"]$/g, '') ?? markdownBody(source).match(/^# (.+)$/m)?.[1] ?? name,
    url: documentRoute(name, source), ...classify(name, source), text: plainText(source),
    readerView: source.includes('Generated by reader-references.mjs'),
    requirementAnchors: requirementAnchors(source),
    requirements: [...source.matchAll(/^#{1,6} (PR-REQ-\d+)\b/gm)].map(m => m[1]),
  }));
  const urls = new Set();
  for (const page of pages) { if (urls.has(page.url)) throw new Error('Duplicate document route: ' + page.url); urls.add(page.url); }
  return {edition: 2, source_digest: documentDigest(documents), pages};
}
export async function commandHelp(root) {
  const cli = await readFile(path.join(root, 'src/cli.rs'), 'utf8');
  const version = (await readFile(path.join(root, 'Cargo.toml'), 'utf8')).match(/^version\s*=\s*"([^"]+)"/m)?.[1];
  const block = cli.match(/const HELP: &str = concat!\(([\s\S]*?)\n\);/)?.[1];
  if (!block || !version) throw new Error('CLI help declaration changed; update the extractor');
  const strings = [...block.matchAll(/"((?:[^"\\]|\\[\s\S])*)"/g)].map(m => m[1] === 'CARGO_PKG_VERSION' ? version : JSON.parse('"' + m[1].replace(/\\\r?\n[ \t]*/g, '') + '"'));
  const text = strings.join('');
  if (!text.startsWith('Pactrun ' + version + '\nUsage:')) throw new Error('Unexpected CLI help');
  return {version, source: 'src/cli.rs', text};
}
export async function exportCatalog(siteDir) {
  const docs = await readDocuments(path.resolve(siteDir, '../docs'));
  const catalog = makeCatalog(docs);
  const output = path.join(siteDir, '.generated-text');
  await mkdir(output, {recursive: true});
  await writeFile(path.join(output, 'document-catalog.json'), JSON.stringify(catalog));
  await writeFile(path.join(output, 'command-help.json'), JSON.stringify(await commandHelp(path.resolve(siteDir, '..'))));
  return catalog;
}
export default function documentCatalog(context) {
  return {
    name: 'pactrun-document-catalog',
    async loadContent() { return exportCatalog(context.siteDir); },
    async contentLoaded({content, actions}) { actions.setGlobalData({source_digest: content.source_digest, help: await commandHelp(path.resolve(context.siteDir, '..')), pages: content.pages.map(({text, ...page}) => page)}); },
    async postBuild({outDir, routesPaths}) {
      const expected = makeCatalog(await readDocuments(path.resolve(context.siteDir, '../docs')));
      const actual = JSON.parse(await readFile(path.join(outDir, 'document-catalog.json'), 'utf8'));
      if (JSON.stringify(expected) !== JSON.stringify(actual)) throw new Error('Document catalog is stale');
      const normalize = route => route.replace(/\/$/, '') || '/';
      const routes = new Set(routesPaths.map(normalize));
      for (const page of actual.pages) if (!routes.has(normalize(context.siteConfig.baseUrl + page.url.slice(1)))) throw new Error('Unpublished search result: ' + page.source);
      await validateRequirementAnchors(outDir, actual.pages);
      const help = JSON.parse(await readFile(path.join(outDir, 'command-help.json'), 'utf8'));
      if (JSON.stringify(help) !== JSON.stringify(await commandHelp(path.resolve(context.siteDir, '..')))) throw new Error('Generated CLI help is stale');
    },
  };
}
