import {readFile, writeFile, mkdir} from 'node:fs/promises';
import path from 'node:path';
import {readDocuments, markdownBody, documentDigest} from '../text-docs/index.mjs';
import {classify} from './model.mjs';
import {editions} from '../editions.mjs';
export {classify} from './model.mjs';

export function documentRoute(name, source) {
  const slug = source.match(/^slug:\s*(\S+)/m)?.[1];
  if (slug) {
    if (!slug.startsWith('/') || slug.includes('..')) throw new Error('Unsupported document slug: ' + name);
    return slug;
  }
  return '/' + name.replace(/\.md$/, '').replace(/(^|\/)index$/, '$1');
}
export function plainText(source) {
  return markdownBody(source)
    .replace(/<details>\s*<summary>(?:Maintainer sources|For Pactrun maintainers) \(optional\)<\/summary>[\s\S]*?<\/details>/g, '')
    .replace(/^(#{1,6}[ \t]+[^\n]+?)[ \t]+\{#[^\n}]+\}[ \t]*$/gm, (_, heading) => heading)
    .replace(/<!--[\s\S]*?-->/g, '').replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/<[^>\n]+>/g, ' ').replace(/[#*\x60|]/g, ' ').replace(/\s+/g, ' ').trim();
}
export function requirementAnchors(source) {
  const anchors = {};
  for (const match of source.matchAll(/^#{1,6} (PR-REQ-\d+)\b([^\n]*)/gm)) {
    const heading = match[1] + match[2];
    const explicit = heading.match(/\s+\{#([^}]+)\}\s*$/)?.[1];
    // The bounded requirement-heading grammar is checked against rendered HTML at build.
    anchors[match[1]] = explicit ?? heading.toLowerCase()
      .replace(/[^\p{L}\p{N}_\-\s]/gu, '').replace(/\s/g, '-');
  }
  return anchors;
}

export async function validateRequirementAnchors(outDir, pages) {
  for (const page of pages.filter(page => Object.keys(page.requirementAnchors).length)) {
    const relative = page.url.slice(1).replace(/\/$/, '');
    let html;
    for (const file of [path.join(outDir, relative + '.html'), path.join(outDir, relative, 'index.html')]) {
      try { html = await readFile(file, 'utf8'); break; }
      catch (error) { if (error.code !== 'ENOENT') throw error; }
    }
    if (html === undefined) throw new Error('Missing rendered contract: ' + page.source);
    for (const [id, anchor] of Object.entries(page.requirementAnchors)) {
      if (!html.includes('id="' + anchor + '"')) throw new Error('Unverified requirement anchor: ' + id + ' in ' + page.source);
    }
  }
}

export function makeCatalog(documents) {
  const pages = documents.filter(([name]) => name.endsWith('.md') && !name.startsWith('agents/')).map(([name, source]) => ({
    source: name,
    title: source.match(/^title:\s*(.+)$/m)?.[1]?.replace(/^['"]|['"]$/g, '') ?? markdownBody(source).match(/^# (.+)$/m)?.[1] ?? name,
    url: documentRoute(name, source), ...classify(name, source), text: plainText(source),
    readerView: source.includes('Generated by reader-references.mjs'),
    requirementAnchors: requirementAnchors(source),
    requirements: [...source.matchAll(/^#{1,6} (PR-REQ-\d+)\b/gm)].map(m => m[1]),
  }));
  const urls = new Set();
  for (const page of pages) { if (urls.has(page.url)) throw new Error('Duplicate document route: ' + page.url); urls.add(page.url); }
  return {edition: 2, source_digest: documentDigest(documents), pages};
}
export async function commandHelp(root) {
  const cli = await readFile(path.join(root, 'src/cli.rs'), 'utf8');
  const version = (await readFile(path.join(root, 'Cargo.toml'), 'utf8')).match(/^version\s*=\s*"([^"]+)"/m)?.[1];
  const block = cli.match(/const HELP: &str = concat!\(([\s\S]*?)\n\);/)?.[1];
  if (!block || !version) throw new Error('CLI help declaration changed; update the extractor');
  const strings = [...block.matchAll(/"((?:[^"\\]|\\[\s\S])*)"/g)].map(m => m[1] === 'CARGO_PKG_VERSION' ? version : JSON.parse('"' + m[1].replace(/\\\r?\n[ \t]*/g, '') + '"'));
  const text = strings.join('');
  if (!text.startsWith('Pactrun ' + version + '\nUsage:')) throw new Error('Unexpected CLI help');
  return {version, source: 'src/cli.rs', text};
}
export async function editionCatalog(siteDir, edition) {
  const docs = await readDocuments(edition.docsDir);
  const catalog = makeCatalog(docs);
  catalog.version = edition.id;
  catalog.pages = catalog.pages.map(page => ({...page, version: edition.id, url: '/' + edition.path + page.url}));
  const help = edition.id === 'current' ? await commandHelp(path.resolve(siteDir, '..'))
    : JSON.parse(await readFile(path.join(siteDir, 'versioned_help', edition.id + '.json'), 'utf8'));
  if (edition.id !== 'current' && help.version !== edition.id) throw new Error('CLI snapshot version mismatch');
  return {...catalog, help};
}
export async function exportCatalog(siteDir, edition) {
  const catalog = await editionCatalog(siteDir, edition);
  const output = path.join(siteDir, '.generated-text', edition.path);
  await mkdir(output, {recursive: true});
  await writeFile(path.join(output, 'document-catalog.json'), JSON.stringify(catalog));
  await writeFile(path.join(output, 'command-help.json'), JSON.stringify(catalog.help));
  return catalog;
}
export default function documentCatalog(context) {
  return {
    name: 'pactrun-document-catalog',
    async loadContent() {
      return Promise.all((await editions(context.siteDir)).map(async edition => ({
        ...edition, ...await exportCatalog(context.siteDir, edition),
      })));
    },
    async contentLoaded({content, actions}) {
      actions.setGlobalData({editions: content.map(({id, label, path: routePath, help, pages}) => ({
        id, label, path: routePath, help, pages: pages.map(({text, ...page}) => page),
      }))});
      const base = context.siteConfig.baseUrl;
      for (const edition of content) {
        for (const name of ['search', 'commands']) actions.addRoute({
          path: base + edition.path + '/' + name,
          component: '@site/src/pages/' + name + '.tsx', exact: true,
        });
      }
      // Keep published unversioned bookmarks (including fragments) working.
      for (const page of content[0].pages) {
        const oldPath = page.url.slice(content[0].path.length + 1) || '/';
        const data = await actions.createData('redirect-' + page.source.replaceAll('/', '_') + '.json', JSON.stringify({to: page.url}));
        actions.addRoute({path: base + oldPath.slice(1), exact: true,
          component: '@site/src/components/LegacyRedirect.tsx', modules: {target: data}});
      }
      const aliases = JSON.parse(await readFile(path.join(context.siteDir, 'spec-redirects.json'), 'utf8'));
      const sections = JSON.parse(await readFile(path.join(context.siteDir, 'spec-section-redirects.json'), 'utf8'));
      for (const edition of content) {
        const canonical = new Set(edition.pages.map(page => page.url));
        for (const [previous, destination] of Object.entries(aliases)) {
          const to = '/' + edition.path + destination;
          if (!canonical.has(to)) throw new Error('Missing Spec redirect target: ' + to);
          const source = '/' + edition.path + previous;
          if (canonical.has(source)) continue;
          const sectionTargets = Object.fromEntries(Object.entries(sections[previous] ?? {}).map(([anchor, route]) => [anchor, '/' + edition.path + route]));
          const data = await actions.createData('spec-alias-' + edition.id + '-' + previous.replaceAll('/', '_') + '.json', JSON.stringify({to, sections: sectionTargets}));
          actions.addRoute({path: base + source.slice(1), exact: true,
            component: '@site/src/components/LegacyRedirect.tsx', modules: {target: data}});
          if (edition.id === content[0].id) actions.addRoute({path: base + previous.slice(1), exact: true,
            component: '@site/src/components/LegacyRedirect.tsx', modules: {target: data}});
        }
      }
    },
    async postBuild({outDir, routesPaths}) {
      const normalize = route => route.replace(/\/$/, '') || '/';
      const routes = new Set(routesPaths.map(normalize));
      for (const edition of await editions(context.siteDir)) {
        const expected = await editionCatalog(context.siteDir, edition);
        const actual = JSON.parse(await readFile(path.join(outDir, edition.path, 'document-catalog.json'), 'utf8'));
        if (JSON.stringify(expected) !== JSON.stringify(actual)) throw new Error('Document catalog is stale');
        for (const page of actual.pages) if (!routes.has(normalize(context.siteConfig.baseUrl + page.url.slice(1)))) throw new Error('Unpublished search result: ' + page.source);
        await validateRequirementAnchors(outDir, actual.pages);
        const help = JSON.parse(await readFile(path.join(outDir, edition.path, 'command-help.json'), 'utf8'));
        if (JSON.stringify(help) !== JSON.stringify(expected.help)) throw new Error('Generated CLI help is stale');
      }
    },
  };
}
