import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Pactrun Spec',
      collapsed: false,
      items: [
        'spec/index', 'spec/glossary', 'spec/catalog',
        {type: 'category', label: 'Foundations', items: [
          'spec/foundations/index',
          'spec/foundations/identity-and-state',
          'spec/foundations/resources-and-versioning',
          'spec/foundations/product-versioning-and-compatibility',
          'spec/foundations/system-model',
        ]},
        {type: 'category', label: 'Observable behavior', items: [
          'spec/behavior/index',
          'spec/behavior/actions-plans-and-runs',
          'spec/behavior/command-and-output-reference',
          'spec/behavior/inputs-secrets-and-readiness',
          'spec/behavior/m4-runtime-capabilities',
          'spec/behavior/m4-snapshot-command-reference',
          'spec/behavior/m5-migration-command-reference',
          'spec/behavior/packages-revisions-and-instances',
          'spec/behavior/snapshots-migrations-and-recovery',
        ]},
        {type: 'category', label: 'Authoring and format contracts', items: [
          'spec/contracts/index',
          'spec/contracts/actions-inputs-and-parameters',
          'spec/contracts/authoring-model',
          'spec/contracts/error-taxonomy-v1',
          'spec/contracts/hook-protocol-v1',
          'spec/contracts/hooks-recovery-and-cleanup',
          'spec/contracts/migrations',
          'spec/contracts/pack-source-yaml-v1',
          'spec/contracts/recipes-and-runtime-content',
          'spec/contracts/revision-core-format-v1',
          'spec/contracts/snapshot-bundle-v1',
          'spec/contracts/snapshot-integrity-format-v1',
          'spec/contracts/snapshot-integrity-format-v2',
          'spec/contracts/snapshots-and-managed-data',
        ]},
        {type: 'category', label: 'Execution and recovery', items: [
          'spec/execution/index',
          'spec/execution/execution-and-concurrency',
          'spec/execution/m4-snapshot-lifecycle-approval-baseline',
          'spec/execution/m5-migration-execution',
          'spec/execution/m7-instance-retirement',
          'spec/execution/recovery-and-reconciliation',
        ]},
        {type: 'category', label: 'Internal persistence', items: [
          'spec/persistence/index',
          'spec/persistence/persistence-schema-v2',
          'spec/persistence/persistence-schema-v3',
          'spec/persistence/persistence-schema-v4',
          'spec/persistence/persistence-schema-v5',
          'spec/persistence/persistence-schema-v6',
          'spec/persistence/persistence-schema-v8',
        ]},
        {type: 'category', label: 'M6.5 Candidate Contracts', items: [
          'spec/contracts/revision-core-format-v2',
          'spec/contracts/pack-source-yaml-v2',
          'spec/contracts/hook-protocol-v2',
          'spec/persistence/persistence-schema-v7',
          'spec/execution/m6-5-service-storage-execution',
          'spec/behavior/m6-5-service-storage-command-reference',
        ]},
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/index', 'development/product-overview',
        'development/reading-paths', 'development/next-milestone',
        'development/implementation-roadmap', 'development/development-and-verification',
        'development/release-readiness',
        'development/product-completion-milestones',
        'development/implementation-guidance', 'development/m4-implementation-status',
        'development/m6-implementation-status',
        'development/m6-5-implementation-status',
        'development/m7-implementation-status',
        'development/design-notes/m7-cleanup-deletion-implementation-baseline',
        'development/spec-migration-review',
        {type: 'category', label: 'Design syntheses and history', items: [
          'development/design-notes/non-identity-metadata-semantic-baseline',
          'development/design-notes/pre-m2-installation-instance-binding-baseline',
          'development/design-notes/service-storage-semantic-baseline',
          'development/design-notes/service-storage-staged-design-alignment',
          'development/design-notes/m6-recovery-implementation-baseline',
          'development/design-notes/m6-5-servicestorage-baseline',
          'development/design-notes/m3-action-execution-approval-baseline',
          'development/design-references', 'development/history/documentation-edition-1',
          'development/history/m8-recipes-rejected',
        ]},
      ],
    },
    {
      type: 'category', label: 'Usage Guides (Planned)', items: [
        'guides/index', 'introduction',
        {type: 'category', label: 'Users (Planned)', items: [
          'pactrun-users/concepts/actions-plans-and-runs',
          'pactrun-users/concepts/inputs-secrets-and-readiness',
          'pactrun-users/concepts/packages-revisions-and-instances',
          'pactrun-users/operations/command-and-output-reference',
          'pactrun-users/operations/snapshots-migrations-and-recovery',
        ]},
        {type: 'category', label: 'Pack authors (Planned)', items: [
          'package-authors/fundamentals/actions-inputs-and-parameters',
          'package-authors/fundamentals/authoring-model',
          'package-authors/fundamentals/recipes-and-runtime-content',
          'package-authors/managed-capabilities/hooks-recovery-and-cleanup',
          'package-authors/managed-capabilities/migrations',
          'package-authors/managed-capabilities/snapshots-and-managed-data',
        ]},
      ],
    },
  ],
};

export default sidebars;
