import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category', label: 'Users', collapsed: true, items: [
        'guides/index', 'guides/installation', 'introduction', 'guides/use-pack',
        {type: 'category', label: 'Choose a task', collapsed: false, items: [
          'guides/configure-inputs', 'guides/run-and-diagnose', 'guides/service-resources',
          'pactrun-users/operations/snapshots-migrations-and-recovery', 'guides/pack-management',
          'guides/recovery', 'guides/retirement', 'guides/data-location',
        ]},
        {type: 'category', label: 'Concepts', items: [
          'pactrun-users/concepts/packages-revisions-and-instances',
          'pactrun-users/concepts/inputs-secrets-and-readiness',
          'pactrun-users/concepts/actions-plans-and-runs',
        ]},
        {type: 'category', label: 'Reference', collapsed: false, items: [
          'pactrun-users/reference/index', 'pactrun-users/reference/vocabulary',
          'pactrun-users/operations/command-and-output-reference', 'pactrun-users/operations/invoke-reference',
          'pactrun-users/reference/command-details', 'pactrun-users/reference/snapshot-details',
          'pactrun-users/reference/migration-details', 'pactrun-users/reference/resource-details',
          'pactrun-users/reference/retirement-details', 'pactrun-users/reference/object-lifecycle',
          'pactrun-users/reference/machine-output', 'pactrun-users/reference/snapshot-limits',
        ]},
      ],
    },
    {type: 'category', label: 'Pack authors', items: [
          'package-authors/index', 'package-authors/setup',
          'package-authors/fundamentals/authoring-model',
          'package-authors/fundamentals/actions-inputs-and-parameters',
          'package-authors/fundamentals/recipes-and-runtime-content',
          'package-authors/managed-capabilities/hooks-recovery-and-cleanup',
          {type: 'category', label: 'Optional capability tutorials', items: [
            'package-authors/managed-capabilities/snapshots-and-managed-data',
            'package-authors/managed-capabilities/migrations',
          ]},
          {type: 'category', label: 'Reference', collapsed: false, items: [
            'package-authors/reference/pack-fields', 'package-authors/reference/service-fields',
            'package-authors/reference/shell-loader', 'package-authors/reference/hook-protocol',
            'package-authors/reference/source-format', 'package-authors/reference/revision-format',
            'package-authors/reference/snapshot-limits',
          ]},
    ]},
    {
      type: 'category',
      label: 'Pactrun Spec',
      collapsed: true,
      items: [
        'spec/index', 'spec/glossary', 'spec/catalog',
        {type: 'category', label: 'Foundations', items: [
          'spec/foundations/index',
          'spec/foundations/system-model',
          'spec/foundations/identity-and-state',
          'spec/foundations/resources-and-versioning',
          'spec/foundations/product-versioning-and-compatibility',
        ]},
        {type: 'category', label: 'Observable behavior', items: [
          'spec/behavior/index',
          'spec/behavior/actions-plans-and-runs',
          'spec/behavior/execution-diagnostics',
          'spec/behavior/command-and-output-reference',
          'spec/behavior/managed-object-lifecycle',
          'spec/behavior/inputs-secrets-and-readiness',
          'spec/behavior/m4-runtime-capabilities',
          'spec/behavior/m4-snapshot-command-reference',
          'spec/behavior/m5-migration-command-reference',
          'spec/behavior/packages-revisions-and-instances',
          'spec/behavior/snapshots-migrations-and-recovery',
        ]},
        {type: 'category', label: 'Authoring and format contracts', items: [
          'spec/contracts/index',
          'spec/contracts/actions-inputs-and-parameters',
          'spec/contracts/authoring-model',
          'spec/contracts/error-taxonomy-v1',
            'spec/contracts/cli-machine-interface',
          'spec/contracts/cli-id-selectors',
          'spec/contracts/hook-protocol',
          'spec/contracts/hooks-recovery-and-cleanup',
          'spec/contracts/migrations',
          'spec/contracts/pack-source',
          'spec/contracts/pack-distribution',
          'spec/contracts/recipes-and-runtime-content',
          'spec/contracts/revision-canonical',
          'spec/contracts/snapshot-bundle',
          'spec/contracts/snapshot-integrity',
          'spec/contracts/snapshots-and-managed-data',
        ]},
        {type: 'category', label: 'Execution and recovery', items: [
          'spec/execution/index',
          'spec/execution/execution-and-concurrency',
          'spec/execution/m4-snapshot-lifecycle-approval-baseline',
          'spec/execution/m5-migration-execution',
          'spec/execution/m5-migration-execution',
          'spec/execution/m7-instance-retirement',
          'spec/execution/recovery-and-reconciliation',
        ]},
        {type: 'category', label: 'Internal persistence', items: [
          'spec/persistence/index',
          'spec/persistence/persistence-baseline',
        ]},
          {type: 'category', label: 'Shell Adapter / Loader', items: [
            'spec/contracts/shell-loader',
          ]},
          {type: 'category', label: 'ServiceStorage', items: [
          'spec/execution/m6-5-service-storage-execution',
          'spec/behavior/m6-5-service-storage-command-reference',
        ]},
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/index', 'development/product-overview',
        'development/next-milestone', 'development/reading-paths',
        'development/implementation-guidance', 'development/development-and-verification',
        'development/documentation-style', 'development/f-documentation-status',
        'development/release-readiness', 'development/design-references',
        {type: 'category', label: 'Delivery records and historical scope', items: [
        'development/implementation-roadmap',
        'development/product-completion-milestones',
        'development/remaining-capability-milestones',
        'development/execution-diagnostics-observability-status',
        'development/object-catalog-history-metadata-status',
        'development/pack-transport-status',
        'development/cli-presentation-status',
        'development/shared-obligation-inventory',
        'development/obligation-audit-2026-09-23',
        'development/verification-gap-closure',
        'development/pre-e-readiness',
        'development/managed-object-lifecycle-status',
          'development/snapshot-capacity-and-restore-status',
          'development/shell-adapter-loader-status',
        'development/m4-implementation-status',
        'development/m6-implementation-status',
        'development/m6-5-implementation-status',
        'development/m7-implementation-status',
        'development/design-notes/m7-cleanup-deletion-implementation-baseline',
        'development/spec-migration-review',
        ]},
        {type: 'category', label: 'Design syntheses and history', items: [
            'development/design-notes/snapshot-capacity-and-restore-baseline',
            'development/design-notes/shell-adapter-loader-baseline',
            'development/design-notes/object-catalog-history-metadata-baseline',
            'development/design-notes/pack-transport-baseline',
            'development/design-notes/cli-presentation-baseline',
            'development/design-notes/e-versioning-redesign-decisions',
            'development/design-notes/e-versioning-s0-plan',
            'development/design-notes/shell-loader-format-activation-review',
          'development/design-notes/non-identity-metadata-semantic-baseline',
          'development/design-notes/pre-m2-installation-instance-binding-baseline',
          'development/design-notes/service-storage-semantic-baseline',
          'development/design-notes/service-storage-staged-design-alignment',
          'development/design-notes/m6-recovery-implementation-baseline',
          'development/design-notes/m6-5-servicestorage-baseline',
          'development/design-notes/m3-action-execution-approval-baseline',
          'development/history/documentation-edition-1',
          'development/history/handoff-before-consistency-review-2026-09-28',
          'development/history/guidance-before-consistency-review-2026-09-28',
          'development/history/m8-recipes-rejected',
        ]},
      ],
    },

  ],
};

export default sidebars;
